### ISSUE TITLE
Unsupported output type when submitting certificate

### ISSUE THREAD

**Issue by jameshilliard** [crtsh/certwatch_db#22]
It appears I'm hitting [this](https://github.com/crtsh/certwatch_db/blob/4bf23255da30de97fb87ce1fb148e79bda276c8f/web_apis.fnc#L247) when trying to submit a certificate generated using the [certificate submission assistant](https://crt.sh/gen-add-chain). The curl POST seemed to work fine when using `https://ct.googleapis.com/pilot/ct/v1/add-chain`.

```
$ curl -X POST https://crt.sh/ct/v1/add-chain --data-binary "@add-chain-1c32fa4eb6430ee7e31551068a70b3c169c17294df923d9a4c0b943bbc2bab32.json"
<BR><BR>Unsupported output type: ct/v1/add-chain</BODY>
</HTML>
```

**Comment by robstradling** [comment]
Hi.  crt.sh is a CT log aggregator.  It isn't a CT log, so it doesn't provide the /ct/v1 endpoints.

The JSON data produced by crt.sh's certificate submission assistant should be POSTed to an actual CT log, as you've discovered.
