### ISSUE TITLE
Timeout with an error webpage rather than an HTTP 404

### ISSUE THREAD

**Issue by robstradling** [crtsh/certwatch_db#30]
Timing out https://crt.sh/ searches with an HTTP 404 has confused lots of people.  It's intended behaviour, but it seems like a bug.

It would be better to return a webpage with a suitably descriptive error message.  I don't think it's possible to do this in the PL/pgSQL code, so this will probably have to be implemented in https://github.com/crtsh/mod_certwatch.

**Comment by robstradling** [comment]
"ERROR:  canceling statement due to conflict with recovery" is the usual error message when a crt.sh query times out.
I think https://github.com/crtsh/mod_certwatch/blob/master/mod_certwatch.c#L446 should return HTTP 503 (Service Unavailable) when PQresultStatus() returns PGRES_FATAL_ERROR, perhaps with the string returned by PQresultErrorMessage() included in the response body.

**Comment by bortzmeyer** [comment]
> "ERROR: canceling statement due to conflict with recovery" is the usual error message when a crt.sh query times out.

This is not the message I got, I had a regular 404 Not Found page.

**Comment by robstradling** [comment]
Sorry, I'll clarify: "ERROR: canceling statement due to conflict with recovery" is the usual error from postgres, but you won't currently see that message in the error responses.  When a postgres error occurs, mod_certwatch currently returns DECLINED to httpd, which causes httpd to return a regular 404 response.
My proposal is to stop returning DECLINED, and instead to return an HTTP 503 with an HTML body that includes the error message from postgres.

**Comment by robstradling** [comment]
Fixed by https://github.com/crtsh/mod_certwatch/commit/3c25aa7217a7dd16890ac6dd191d984b4219d34a

**Comment by bortzmeyer** [comment]
Thanks!
