### ISSUE TITLE
Recompute trusted boxes for CAs whenever a new CA:TRUE is inserted

### ISSUE THREAD

**Issue by alex** [crtsh/certwatch_db#31]
Currently these recompute hourly I believe; it'd be great if they recompute as soon as new CA:TRUE certs are inserted into the DB.

**Comment by robstradling** [comment]
@alex I've just updated the recompute from hourly to ten-minutely.  I hope that's sufficient for your needs.

The recompute is also necessary after a CA cert expires or is revoked, so I can't switch to an "as soon as new CA:TRUE certs are inserted" model instead.
