### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by stayallive** [crtsh/certwatch_db#35]
For science and fun I am trying to run crt.sh on my own hardware however it looks like I am running against some bottlenecks regarding performance. I am wondering if I am missing something. It looks like most time is spent inside the `import_ct_cert` function (obviously 🤣 ) however trying to find out which query inside (or insede `import_cert`) might be hauling this amount of rows has not been acomplished yet (which looks to be the biggest bottleneck).

![screen shot 2017-08-09 at 00 40 51](https://user-images.githubusercontent.com/1090754/29097736-bb290998-7c9b-11e7-8e17-3fcfff395d82.png)

When I started with an empty database (right now I have about 60M certs imported) it went a lot faster and was mostly bottlenecked by disk I/O however now it looks like to be CPU (the import query hogging a Postgres thread).

I was wondering if you have any idea why this is happening and what I could do to optimize since right now the google log is growing faster then I can import.

Also wondering what kind of hardware / setup crt.sh is using (figured a 4 SSD RAID10 with plenty of cores and ram would do the trick easily) 👀

**Comment by robstradling** [comment]
Hi.  Well done for getting that far, given the lack of documentation!

It could just be underpowered hardware.  In Feb 2017, we upgraded the crt.sh master DB server to roughly the same setup as you suggested.  The previous server was old, underpowered and lacked SSDs, and we'd reached the point that the logs were growing faster than we could import.

BTW, if you do spot any optimization opportunities in the codebase, please let me know!  :-)

**Comment by stayallive** [comment]
It took a lot of nights trying all the buttons and options :) But it seems mostly running now 👍 

Hmm, might still be a bottleneck somewhere but it's very hard to profile since I cannot repeat the import query (because the cert already exists ofcourse) and doing it step by step does not seem te be highlighting where te time is spent. Postgres itself is also not helping, profiling when running just says all time is spent in the import_cert which I already knew ofcourse.

The rows returned is still climbing while inserted is getting lower, there is probably a query that needs some kind of sorting that postgres cannot use an index for and is thus doing it in memory causing the CPU to spike instead of I/O (CPU is fairly limited since it's a single thread compared to the 4 SSD RAID I/O when reading indexes), it's really bad for Let's Encrypt certificates it seems (which has issues the most certificates in the state where my DB is in currently), does that give you an idea where to start digging? Al queries seem to simple to be causing any issues at all and don't seem to do alot of searching except on indexes which should not cause these numbers (returned and fetched should be about equel for a indexed sort or lookup I believe).

**Comment by stayallive** [comment]
@robstradling it seems like Vacuum / Analyze has a massive impact on the insert performance and those settings were not optimized enough on my instance. Now taking in 100k rows / hour instead of the few hundred. Now running vacuum/analyze every 5k changes, what kind of vacuum strategy is the crt.sh master using?
