### ISSUE TITLE
Add 'Upload' to https://crt.sh/lintcert

### ISSUE THREAD

**Issue by ericlaw1979** [crtsh/certwatch_db#37]
It'd be nice if there were an "Upload" button on the lintcert HTML form.

Sample code e.g. https://twitter.com/ericlaw/status/916342499790204930

<script>
function handleFiles() {
    var reader = new FileReader();
    reader.onload = function(e) {
      var str = reader.result;
       if (str.startsWith("-----BEGIN CERTIFICATE-----")) {
            str = str.slice(28);
            let ixLastDash = str.indexOf("-");
            if (ixLastDash>0) str = str.slice(0,ixLastDash);
       }
       document.getElementById("b64cert").innerText = str;
    }
    reader.readAsText(document.getElementById("fil").files[0]);
}
</script>
</HEAD>
<BODY>
  <A href="/"><SPAN class="title">crt.sh</SPAN></A>  <SPAN class="whiteongrey">Certificate Linter</SPAN>
<BR><BR>1. Enter a base64 encoded Certificate or pick a file: <input type="file" id="fil" onchange="handleFiles(this.files)" />
<BR><BR>2. Press the "Lint Certificate" button.
<BR><BR><FORM method="post">
  <TEXTAREA name="b64cert" id="b64cert" rows=25 cols=64></TEXTAREA>

**Comment by robstradling** [comment]
Addressed by https://github.com/crtsh/certwatch_db/commit/4ca42bdd18deab4fa7b66922c63a0f4f88b8ff58

Thanks Eric.

**Comment by ericlaw1979** [comment]
Thank you!
