### ISSUE TITLE
Create foreign key constrained on table crl_revoked to table ca

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#39]
To increase the speed of a search for revoked certificates of a specific CA it would be helpful to have a foreign key relation between the table `crl_revoked` to the table `ca`

```
CONSTRAINT crl_revoked_ca_fk
		FOREIGN KEY (CA_ID)
		REFERENCES ca(ID)
```

**Comment by robstradling** [comment]
@RufusJWB FK constraint added.  Thanks.

**Comment by RufusJWB** [comment]
when will you roll it out to crt.sh?

**Comment by robstradling** [comment]
Already done.  :-)

**Comment by RufusJWB** [comment]
And already used :-) This is a great service you offer here
