### ISSUE TITLE
There is no parameter $3

### ISSUE THREAD

**Issue by clintwilson** [crtsh/certwatch_db#4]
When trying to view https://crt.sh/?cablint=226&iCAID=1687, I receive the following:

For certificates with notBefore >= 2016-02-02: 

> There is no parameter $3
>
> PL/pgSQL function web_apis(text,text[],text[]) line 1347 at EXECUTE statement
> 
> SELECT c.ID, x509_subjectName(c.CERTIFICATE) SUBJECT_NAME, x509_notBefore(c.CERTIFICATE) NOT_BEFORE, x509_notAfter(c.CERTIFICATE) NOT_AFTER FROM certificate c , cablint_cert_issue cci WHERE c.ISSUER_CA_ID = $1::integer AND c.ID = cci.CERTIFICATE_ID AND cci.ISSUER_CA_ID = $1::integer AND cci.NOT_BEFORE >= $3 AND cci.CABLINT_ISSUE_ID = $2::integer GROUP BY c.ID, SUBJECT_NAME, NOT_BEFORE, NOT_AFTER ORDER BY NOT_BEFORE DESC OFFSET 0 LIMIT 100

It looks like the notBefore is not associating with the correct variable/parameter (?)

**Comment by robstradling** [comment]
Thanks Clint.  This problem has now been fixed.
