### ISSUE TITLE
No Let's Encrypt displayed in 1 week summary

### ISSUE THREAD

**Issue by patryk** [crtsh/certwatch_db#40]
Hi,

Let's Encrypt is no longer displayed in 1 week summary screen, e.g.:
https://crt.sh/?cablint=1+week&dir=^&sort=3

Although any other search displays them correctly.

**Comment by robstradling** [comment]
When Let's Encrypt started issuing precertificates earlier this year, the crt.sh servers started to struggle to keep up with the increased log growth rate.  As a (hopefully temporary) hack to attempt to deal with this performance problem, I disabled crt.sh's automated linting of certs issued by "Let's Encrypt Authority X3" (https://crt.sh/?caid=16418).
I plan to overhaul crt.sh's log monitor application (https://github.com/crtsh/ct_monitor) to make it more performant.  After that, it should be possible to re-enable linting for CA 16418.

Thanks for filing this issue.  I'll leave it open until I've been able to adequately address the performance challenges.

**Comment by robstradling** [comment]
The new crt.sh service just went live (see https://crt.sh/forum?place=msg%2Fcrtsh%2FDM8SI-qsE8E%2Fd9AtKFD5BgAJ).  I was able to overhaul the automated linting to make it more performant, and so Let's Encrypt certs are now being automatically linted once again.
