### ISSUE TITLE
Create index on ct_log_entry to improve speed

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#41]
To increase the speed of a search for the first time a certificate showed up in any CT log, it would be (hopefully) helpful to have an additional index:

`CREATE INDEX ctle_et_ci
	ON ct_log_entry (ENTRY_TIMESTAMP, CERTIFICATE_ID);`

Could you please add this? Honestly I have to admit, I'm not 100% sure it will help, but I'm running out of ideas how to speed up my query otherwise.

**Comment by RufusJWB** [comment]
I think the problem comes from somewhere else. I'll close this issue

**Comment by robstradling** [comment]
There's already an index on ENTRY_TIMESTAMP, so the index you proposed wouldn't make any significant difference.
Feel free to ask on the crt.sh forum (https://crt.sh/forum) if you need assistance with writing SQL to query the crt.sh DB.

**Comment by RufusJWB** [comment]
I wasn't aware there is forum for crt.sh . Very nice. I got my problem solved rewriting my query to use a the keyword `LATERAL` which increased the performance dramatically: https://dba.stackexchange.com/questions/208808/inefficient-execution-plan-selected-by-postgresql/208974

**Comment by robstradling** [comment]
Nice.  Thanks for the tip.  :-)
