### ISSUE TITLE
Precertificates not shown correctly?

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#42]
I think, there is a problem with parsing precertificates for this certificate: https://crt.sh/?id=501788710

![image](https://user-images.githubusercontent.com/1633499/41048110-538534dc-69ae-11e8-9d07-9d67066bf5a2.png)

Both are dating back to Sept. 2017  but only one is shown in the overview:

![image](https://user-images.githubusercontent.com/1633499/41048161-6b1286e0-69ae-11e8-9b05-7435f9993359.png)

Is it possible, that there is a problem in parsing CT logs?

**Comment by robstradling** [comment]
That screenshot (taken from https://crt.sh/?id=501788710) shows the precertificate SCTs that have been embedded in the final certificate, whereas the list at the top of the same page shows the logs that have accepted the final certificate.
To see the list of logs that have accepted the precertificate, you need to look at the crt.sh page for the precertificate.  Click on the "Precertificate" link (see your screenshot), and you'll arrive at https://crt.sh/?id=208763734.
