### ISSUE TITLE
Table has_debian_weak_key is not accessiable

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#44]
I think there is a problem with the access rights to the table has_debian_weak_key. Could you please check this? Thank you!

![image](https://user-images.githubusercontent.com/1633499/41594585-1fbd5920-73c4-11e8-8a30-829299d225d9.png)

**Comment by robstradling** [comment]
Thanks.  Fixed.

certwatch@certwatch=> grant select on has_debian_weak_key to guest;
GRANT

**Comment by RufusJWB** [comment]
Thank you! I made two small queries to simplify working with it:  https://gist.github.com/RufusJWB/c29836420f78899b8a3f978104f7a703 
and 
https://gist.github.com/RufusJWB/f8818c60e071a98f0005d3471e94334e
