### ISSUE TITLE
Make OCSP responder test queries identifiable 

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#46]
It would be great, if you could make the OCSP responder test queries for unknown certificates somehow identifiable, e.g. by letting the random serial number always start with '0f0f0f'. The background for this request is, that our OCSP monitoring always sends an alert when a request for an unknown certificate have been logged. This logging can't be easily filtered for the IP address of the requesting address and would need always manual digging in other log files. If you would embed such a magic string in the serial number, we could easily filter for them.

What do you think?

**Comment by robstradling** [comment]
Hi @RufusJWB .  Unknown serial numbers now have the following prefix: 6372742E7368 (that's "crt.sh" in hex).

**Comment by robstradling** [comment]
Fixed by https://github.com/crtsh/ocsp_monitor/commit/101efd7e4d0c428291e22e10f7591681387d9fa6
