### ISSUE TITLE
Identity Search fails on crt.sh

### ISSUE THREAD

**Issue by stamster** [crtsh/certwatch_db#47]
I'm not sure whenever this is the right spot to report the problem on the website https://crt.sh

# Problem description

> incompatible library "/usr/lib64/postgresql-9.5/lib64/libx509pq.so": version mismatch

> PL/pgSQL function web_apis(text,text[],text[]) line 3084 at assignment

# Steps to reproduce
https://crt.sh/?q=www.google.com

**Comment by robstradling** [comment]
Thanks.  Our ops team spun up some new front-end servers for crt.sh a couple of days ago, and there were a few teething troubles.  Should be fixed now, but please comment on this ticket again if you see this problem recur.

**Comment by robstradling** [comment]
I received another report this morning about this error.  It turned out that there was a new front-end server that I hadn't been told about.  It's also now fixed.
