### ISSUE TITLE
Create SQL JOIN statement to take fields from multiple tables such as Certfificate_table and CA_table

### ISSUE THREAD

**Issue by bedford1234** [crtsh/certwatch_db#50]
Hello,

I would like to create a SQL JOIN statement to take fields from multiple tables such as Certfificate_table and CA_table in the PostgreSQL.. What is the best way to do this? I would greatly appreciate your help!

**Comment by RufusJWB** [comment]
Have a look here: https://github.com/crtsh/certwatch_db/issues/45 Maybe it helps
