### ISSUE TITLE
How often do you read the CCADB in?

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#55]
I'm wondering, how often do you update the information in crt.sh with the information in CCADB? I did some queries in crt.sh on the information coming from CCADB and it turned out, that the completeness of the data is not very satisfying. Now I'm wondering, if the data is not in CCADB (which I can't access) or if there is a problem in the import of CCADB data.

**Comment by robstradling** [comment]
crt.sh currently downloads and processes [1] every ten minutes and [2] every one hour.

[1] https://ccadb-public.secure.force.com/mozilla/AllCertificateRecordsCSVFormat
[2] https://ccadb-public.secure.force.com/mozilla/CAInformationReportCSVFormat

**Comment by robstradling** [comment]
Can you be more specific on what data you think might be lacking?

**Comment by RufusJWB** [comment]
I clarified with Kathleen, that this information I was looking for (the audit regime (webtrust or ETSI)) is also not in every line of the CCADB. I'll close this issue. Thank you for the reply!
