### ISSUE TITLE
Support HTTP Accept Header

### ISSUE THREAD

**Issue by fharding1** [crtsh/certwatch_db#56]
The API currently uses the `output` URL query parameter to specify the returned content type. For example:

`curl 'https://crt.sh/?q=%.example.com&output=json'`

However, it does not support the [Accept](https://tools.ietf.org/html/rfc2616#section-14.1) header which is part of the HTTP specification.

To not break existing tools, it would probably be fine to keep the `output` URL parameter, but also add the ability to specify the content type via `Accept`, like:

`curl 'https://crt.sh/?q=%.example.com' -H 'Accept: application/json'`

**Comment by robstradling** [comment]
Fixed by https://github.com/crtsh/mod_certwatch/commit/1edf24e31455d930edeb59585fdcbf4892b017c0

Thanks for the suggestion.

**Comment by fharding1** [comment]
Awesome! Thanks for adding that :tada:
