### ISSUE TITLE
I can not find Symantec Class 1 Public Primary Certification Authority - G7

### ISSUE THREAD

**Issue by DanielRuf** [crtsh/certwatch_db#60]
It seems this and a few more are not in the database.
I have to check if it has child CAs and which it has.

**Comment by DanielRuf** [comment]
https://crt.sh/?Identity=Symantec+Class+1+Public+Primary+%25

**Comment by DanielRuf** [comment]
https://www.websecurity.symantec.com/theme/roots
Is it because of
> Hierarchy: Client Auth/Email

?

**Comment by robstradling** [comment]
Presumably "Symantec Class 1 Public Primary Certification Authority - G7" has never been submitted to, and accepted by, any of the CT logs that crt.sh monitors.
