### ISSUE TITLE
Time outs on querying large CAs

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#61]
I wrote a little query to find all certificates with 63 bits or shorter serial numbers:

```
SELECT concat('https://crt.sh/?id=', cert_lc.certificate_id,'&opt=ocsp'), cert_lc.subject_distinguished_name, not_before, not_after, substr(encode(cert.certificate, 'hex'), 27, 2) datatype, substr(encode(cert.certificate, 'hex'), 29, 2) snlength
FROM certificate_lifecycle cert_lc
JOIN certificate cert
ON cert.id = cert_lc.certificate_id
where cert_lc.ca_id = 52410 AND cert_lc.expired = false AND cert_lc.revoked = 0 AND cert_lc.not_before < '2018-03-01' and cert_lc.certificate_type = 'Precertificate'and  ('x' || lpad(substr(encode(cert.certificate, 'hex'), 29, 2), 8, '0'))::bit(32)::int <= 8
order by not_before desc
```

It works very good on small CAs but gets time outs for CAs with more than a couple of thousand certificates. Does anybody has an idea how to improve this?

**Comment by robstradling** [comment]
Hi @RufusJWB.  I've just kicked this off on the crt.sh master database (which doesn't time out long-running queries)...

```
CREATE TABLE serial_number_entropy_20190313 AS
SELECT sub.ISSUER_CA_ID,
       SUM(CASE WHEN sub.SERIAL_BIT_LENGTH >= 64 THEN 1 ELSE 0 END) SIXTY_FOUR_OR_MORE,
       SUM(CASE WHEN sub.SERIAL_BIT_LENGTH < 64 THEN 1 ELSE 0 END) SIXTY_THREE_OR_LESS
  FROM (
         SELECT c.ISSUER_CA_ID,
                serial_number_bitlength(x509_serialNumber(c.CERTIFICATE)) SERIAL_BIT_LENGTH
           FROM certificate c
           WHERE x509_notBefore(c.CERTIFICATE)
                   BETWEEN '2016-09-30'::date    -- Effective date of "at least 64 bits of output from a CSPRNG."
                       AND '2019-02-22'::date    -- Date when Wayne started the m.d.s.p discussion about DM.
  ) sub
  GROUP BY sub.ISSUER_CA_ID;
```
I expect it'll take a day or two for this to complete!  Once it's finished, I'll share the results.  (Please poke me if I forget ;-) ).

BTW, serial_number_bitlength() is a new function I just added (https://github.com/crtsh/certwatch_db/commit/e4e196e1e5efcb63d601936be3291e2098f07135).

**Comment by RufusJWB** [comment]
Cool. Thank you! One remark: If I understand `serial_number_bit_length()` correctly, you are calculating the bit length of the serial number. You can also directly parse them from ASN.1, as I do in my original query. And of course we have to be aware, that there is a slight chance, that a serial number is less than 64 bits but still contain 64 bits of random data...

**Comment by robstradling** [comment]
@RufusJWB Sorry, I couldn't quite get my head around your technique, so I chose to write a function I could understand.  ;-)
It's more than a "slight chance".  In 64-bits of output from a CSPRNG, we should expect the MSB to be zero 50% of the time.  Once my query completes, any record where SIXTY_THREE_OR_LESS > 0 *and* where SIXTY_FOUR_OR_MORE = 0 (or is significantly less than SIXTY_THREE_OR_LESS) will be worthy of closer scrutiny.

**Comment by RufusJWB** [comment]
Thank you @robstradling  for the clarification:

> Once my query completes, any record where SIXTY_THREE_OR_LESS > 0 and where SIXTY_FOUR_OR_MORE = 0 (or is significantly less than SIXTY_THREE_OR_LESS) will be worthy of closer scrutiny.


Now I understand the idea of this table. Having two columns is a great approach!

**Comment by robstradling** [comment]
This query completed.  I've posted a message about it to m.d.s.p: https://www.mail-archive.com/dev-security-policy@lists.mozilla.org/msg11740.html

**Comment by RufusJWB** [comment]
Could you please add in line 173 ( C=DE, ST=Bayern, L=Muenchen, O=Siemens, serialNumber=ZZZZZZB9, OU=Siemens Trust Center, CN=Siemens Issuing CA Internet Server 2017
) the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1534535 dating from 2019-03-12 ? That was somehow missed.

**Comment by robstradling** [comment]
@RufusJWB Sorry about that.  I'm not sure how that got missed.  I've added it.
