### ISSUE TITLE
I could not find installation instructions 

### ISSUE THREAD

**Issue by AKKlostermann** [crtsh/certwatch_db#62]
This may be a stupid question/issue/request but I really couldn't figure out where the installation instructions for this repository are. Or which of the crtsh repositories is the one to start with.

There are container images on dockerhub.com but they don't contain source code or Dockerfile recipes, so I can't trust them.

Maybe I can figure out on my own how to install this stuff in postgres, but I thought I might politely request some hints here!

**Comment by robstradling** [comment]
This (certwatch_db) is the main repository for the database and web application.  The code is the documentation, I'm afraid.  Enabling others to run local instances of crt.sh is not a goal I can commit any time to.

I don't know anything about any container images on dockerhub.com.
