### ISSUE TITLE
Make `certificate_lifecycle` a materialized view

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#63]
Do you think it would be possible to change the `certificate_lifecycle` [view](https://github.com/crtsh/certwatch_db/blob/e4e196e1e5efcb63d601936be3291e2098f07135/create_schema.sql#L912) into a [materialized view](https://spin.atomicobject.com/2018/04/09/postgres-materialized-views/)? This would highly improve the speed of querying this view - but of course will take a lot of memory. Additionally it would be necessary to define an update cycle, I think every 30 minutes or even every hour would be enough. [SO](https://stackoverflow.com/a/29447328/1426535) describes some possible options to do so. I think for our scenario, the CRON-job would be very well suited, as we don't have the requirement of always being up-to-date to the latest change.

**Comment by robstradling** [comment]
Hi @RufusJWB.  I'm afraid it's not practical to do this.  The master database server already has its work cut out keeping up with the growth rate of the monitored logs.  Continually updating this proposed materialized view would hurt performance too much; and I'm pretty sure that each update would take several days to complete.  And disk space is not free or unlimited.  :-(

**Comment by RufusJWB** [comment]
hi @robstradling  hm, that's so sad. The reason for creating this issue is, that it often takes a long time to execute this view, especially for CAs with a lot of issued certificates. Maybe creating some more indices could help improving the speed. Maybe you as administrator have some more performance measuring tools available to find out, which indices are missing / would helpful?
