### ISSUE TITLE
ERROR:  permission denied for relation certificate_lifecycle

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#64]
Suddenly i receive the error

> ERROR:  permission denied for relation certificate_lifecycle
> SQL state: 42501

when trying to execute the following statement

`SELECT * FROM public.certificate_lifecycle WHERE ca_id = 52410`.

Do you have any idea what happened?

**Comment by robstradling** [comment]
Hi @RufusJWB.  I'm not sure what happened.

I've just dropped and re-created this VIEW (and run GRANT SELECT ON certificate_lifecycle TO GUEST).  That seems to have done the trick.
