### ISSUE TITLE
Error when searching for SHA-1(SubjectPublicKeyInfo)

### ISSUE THREAD

**Issue by exploide** [crtsh/certwatch_db#68]
In Advanced Search, when selecting SHA-1(SubjectPublicKeyInfo) and trying to search for a hash, the following error appears:

```
column "bytea" does not exist

PL/pgSQL function web_apis(text,text[],text[]) line 206 at IF
```

**Comment by robstradling** [comment]
Thanks.  Fixed by https://github.com/crtsh/certwatch_db/commit/5cd86936259183e5f246789bce5cd286f30a53ad
