### ISSUE TITLE
Make the revocation status table aware if the certificate has expired

### ISSUE THREAD

**Issue by sleevi** [crtsh/certwatch_db#73]
The [revocation status computation](https://github.com/crtsh/certwatch_db/blob/cb204d8d38833281bc04877dea0992d8880daafc/fnc/web_apis.fnc#L2035-L2167) has the default status of a certificate as 'Not Revoked', typically via code in the form

`t_temp2 := coalesce(t_temp2, 'Not Revoked');`

It would be great if it highlighted if a certificate was expired, so that the 'not revoked' status could be better contextualized that it revocation data may not be expected. That is, something where the priority is:
- If affirmatively revoked, show that status
- if `coalesce(x509_notAfter(c.CERTIFICATE), ''infinity''::timestamp) < now()`, show 'Expired'
- else, 'Not revoked'

**Comment by robstradling** [comment]
@sleevi Thanks for suggesting this change.
Fixed by https://github.com/crtsh/certwatch_db/commit/92ad53bde406a31088a766768ec4c4cf6baeba41.
A CRL does not indicate "this certificate is expired", so "Not Revoked (Expired)" seemed a bit more accurate than just "Expired".
