### ISSUE TITLE
Test OCSP responders for https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/G7s5tFR4BAAJ

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#80]
I would like to ask if you could enhance https://crt.sh/ocsp-responders with tests for https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/cMegyySSqhM/m/G7s5tFR4BAAJ

**Comment by robstradling** [comment]
@RufusJWB Thanks for the suggestion.  I think this will be fairly easy to implement.

**Comment by robstradling** [comment]
Tests added to ocsp_monitor by https://github.com/crtsh/ocsp_monitor/commit/e9deaebade1844d07ffd68cb71e908dad3e635dd
https://crt.sh/ocsp-responders updated by https://github.com/crtsh/certwatch_db/commit/3bab0fa1dee44791f9982bcff96bc4779ae4d1c4
