### ISSUE TITLE
SQL Error while filtering OCSP responders

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#85]
While filtering the OCSP responders, I received the following error:

![image](https://user-images.githubusercontent.com/1633499/159004569-9e893da6-39a4-42a4-bc08-c02f6a21e07a.png)

You can reproduce it with this URL: https://crt.sh/ocsp-responders?trustedExclude=&trustedBy=&trustedFor=&dir=v&sort=2&url=&get=&post=&getrandomserial=&postrandomserial=&getforwardslashes=&getunencodedplus=%25400%25&getsha256certid=

**Comment by robstradling** [comment]
Fixed by https://github.com/crtsh/certwatch_db/commit/572ab7da6b276dcf38905ad319578dd6fee07724
