### ISSUE TITLE
Add list of CA certificates trusted by Gmail for S/MIME to the "Trust overview" page

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#91]
It would be great if we could get one more column on this page which should displays the trust of a CA in Gmail.

<img width="617" alt="image" src="https://github.com/crtsh/certwatch_db/assets/1633499/273934e6-92df-451a-9dbb-a4be975195c4">

You can get the list of trusted CAs from Google https://support.google.com/a/answer/7448393?hl=en

**Comment by robstradling** [comment]
@RufusJWB Thanks for the suggestion!  Implemented by https://github.com/crtsh/certwatch_db/commit/40cbe7343771c435fcef92d59015906759b3a2a1 and https://github.com/crtsh/root_programs/commit/49ed555147d881bf8af111e7e43a51f0214ae7f4.
